### ISSUE TITLE
Plugin is broken again...

### ISSUE THREAD

**Issue by anantmishra** [ram2141/einthusan#1]
Plugin is broken again with the following error in the logs:

2020-03-10 14:49:23.987 T:1443877760   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.einthusan/default.py", line 653, in <module>
                                                function_map[mode](name, url, language, mode)
                                              File "/storage/.kodi/addons/plugin.video.einthusan/default.py", line 401, in play_video
                                                get_movie(s,mainurl,mainurlajax, headers)
                                              File "/storage/.kodi/addons/plugin.video.einthusan/default.py", line 413, in get_movie
                                                lnk=re.findall('data-ejpingables=["\'](.*?)["\']',htm)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-03-10 14:49:24.147 T:1937031184   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.einthusan/?url=Pati+Patni+Aur+
Woh%2C7Gsl%2Chindi%2Citsnothd%2Chttps%3A%2F%2Feinthusan.ca%2Fmovie%2Fresults%2F%3Ffind%3DYear%26amp%3Blang%3Dhindi%26amp%3Bpage%3D4%26amp%3Byear%3D201
9&mode=2&name=Pati+Patni+Aur+Woh&lang=hindi&description=Chintu+Tyagi+is+an+ordinary%2C+middle+class+man+who+finds+himself+torn+between+his+wife+and+an
other+woman.A+remake+of+the+1978+film+of+same+name.]

**Comment by anantmishra** [comment]
I would like to take the opportunity to thank you for the wonderful work you are doing for the community. Will appreciate if you could look into the error and provide a fix.

Do let me know if you need any further logs/info.

**Comment by ram2141** [comment]
Hello @anantmishra,

Thank you so much for your kind words. I have a fixed repository. You can uninstall the old repository and install it new from the below link. Feel free to contact me if you have any trouble installing this.

[plugin.video.einthusan.zip](https://github.com/ram2141/einthusan/blob/master/plugin.video.einthusan.zip?raw=true)

**Comment by anantmishra** [comment]
Hi @ram2141.

Thanks a lot for providing the fix. I can confirm that it works perfect!

**Comment by rudhra7** [comment]
> Hello @anantmishra,
> 
> Thank you so much for your kind words. I have a fixed repository. You can uninstall the old repository and install it new from the below link. Feel free to contact me if you have any trouble installing this.
> 
> [plugin.video.einthusan.zip](https://github.com/ram2141/einthusan/blob/master/plugin.video.einthusan.zip?raw=true)

Dear it worked but now again error. Can I please check kodi 18.6 on Samsung tv

**Comment by rudhra7** [comment]
Dear plugin is broken again can u plz fix
