### ISSUE TITLE
Eithusan error

### ISSUE THREAD

**Issue by ghost** [ram2141/einthusan#3]
Hello the plugin is giving error when opening film .

Read error . 

Thanks

**Comment by ram2141** [comment]
Hello @donsai007,

You can uninstall the old repository and install it new from the below link. Feel free to contact me if you have any trouble installing this.

[plugin.video.einthusan.zip](https://github.com/ram2141/einthusan/blob/master/plugin.video.einthusan.zip?raw=true)

**Comment by ghost** [comment]
Hello i unistall old and then new also try with a fresh install getting error eithusan error

**Comment by eintamil** [comment]
Hello, try EinTamil Repo: https://eintamil.github.io/
Please use Einthusan2 for Kodi 18.x (Python 2.x)
Please use Einthusan3 for Kodi 19.x (Python 3.x)
If any issues, raise at https://github.com/eintamil/repository.eintamil/issues
